// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjY-N7_KSV5Y6NJ5SE0PTfuZzf4vuJXkM',
    appId: '1:985694138807:web:33e453f36c57eaca353832',
    messagingSenderId: '985694138807',
    projectId: 'chat-app-flutter-learn',
    authDomain: 'chat-app-flutter-learn.firebaseapp.com',
    storageBucket: 'chat-app-flutter-learn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9GLh3m8D0hMxMbXktoTyYa5n7bbJI6nQ',
    appId: '1:985694138807:android:8aaa3570461931f5353832',
    messagingSenderId: '985694138807',
    projectId: 'chat-app-flutter-learn',
    storageBucket: 'chat-app-flutter-learn.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjY-N7_KSV5Y6NJ5SE0PTfuZzf4vuJXkM',
    appId: '1:985694138807:web:f7fee07aceb4a927353832',
    messagingSenderId: '985694138807',
    projectId: 'chat-app-flutter-learn',
    authDomain: 'chat-app-flutter-learn.firebaseapp.com',
    storageBucket: 'chat-app-flutter-learn.appspot.com',
  );

}