// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcaq4IciC3LsCYwECpfMo7hch8ZQM-c5Y',
    appId: '1:292663948122:web:f42d22e50ec27403c23963',
    messagingSenderId: '292663948122',
    projectId: 'vettigroup-family',
    authDomain: 'vettigroup-family.firebaseapp.com',
    storageBucket: 'vettigroup-family.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAilkoS4S1458Rt1oqCE5Ke8ztlquG1GL0',
    appId: '1:292663948122:android:fae8e2709c20dcffc23963',
    messagingSenderId: '292663948122',
    projectId: 'vettigroup-family',
    storageBucket: 'vettigroup-family.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcaq4IciC3LsCYwECpfMo7hch8ZQM-c5Y',
    appId: '1:292663948122:web:2361ab2a9bf2f204c23963',
    messagingSenderId: '292663948122',
    projectId: 'vettigroup-family',
    authDomain: 'vettigroup-family.firebaseapp.com',
    storageBucket: 'vettigroup-family.appspot.com',
  );
}
