// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNIzQ0KNHJ_b7Bje8br_1k67kaLpaKtSY',
    appId: '1:709745592663:web:b84c4b4ff0ec79cf5cd612',
    messagingSenderId: '709745592663',
    projectId: 'noku-list',
    authDomain: 'noku-list.firebaseapp.com',
    databaseURL: 'https://noku-list-default-rtdb.firebaseio.com',
    storageBucket: 'noku-list.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6NMIJUqhk1IE1XxvwJbx4Fzm87Re0fQQ',
    appId: '1:709745592663:android:9f6391b53d22fc685cd612',
    messagingSenderId: '709745592663',
    projectId: 'noku-list',
    databaseURL: 'https://noku-list-default-rtdb.firebaseio.com',
    storageBucket: 'noku-list.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNIzQ0KNHJ_b7Bje8br_1k67kaLpaKtSY',
    appId: '1:709745592663:web:b84c4b4ff0ec79cf5cd612',
    messagingSenderId: '709745592663',
    projectId: 'noku-list',
    authDomain: 'noku-list.firebaseapp.com',
    databaseURL: 'https://noku-list-default-rtdb.firebaseio.com',
    storageBucket: 'noku-list.appspot.com',
  );

}